---

- name: install apache2
  apt: name=apache2 state=present
  sudo: yes
          
- name: clear old webui module
  file: path=/var/www_bk state=absent
  sudo: yes          
          
- name: backup webui module
  command: mv /var/www/ /var/www_bk/
  sudo: yes
  ignore_errors: True

- name: deploy webui module
  copy: src={{ src_webui_dist }} dest=/var/www/
  sudo: yes

- name: restart apache2
  service: name=apache2 state=restarted
  sudo: yes
