---

- name: install apache2
  apt: name=apache2 state=present
  sudo: yes
          
- name: copy apache settings
  copy: src=etc/apache2/ dest=/etc/apache2/
  sudo: yes
          
- name: disable default site 
  command: a2dissite {{ item }}
  sudo: yes
  with_items:
    - 000-default
    - 000-default.conf
  ignore_errors: True
          
- name: enable simple-taskboard site 
  command: a2ensite simple-taskboard.conf
  sudo: yes

- name: enable modules 
  apache2_module: state=present name={{ item }}
  sudo: yes
  with_items:
    - proxy
    - proxy_ajp
          
- name: clear old webui module
  file: path=/var/www/html_bk state=absent
  sudo: yes          
          
- name: backup webui module
  command: mv /var/www/html/ /var/www/html_bk/
  sudo: yes
  ignore_errors: True

- name: deploy webui module
  copy: src=dist/ dest=/var/www/html/
  sudo: yes

- name: restart apache2
  service: name=apache2 state=restarted
  sudo: yes
