---

- name: prepare jenkins install
  apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present
  sudo: yes
          
- name: prepare jenkins install
  raw: sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
  sudo: yes
          
- name: install jenkins
  apt: name=jenkins state=latest
  sudo: yes
          
- name: copy jenkins binary from project
  command: cp -f {{ jenkins_binary }} /usr/share/jenkins/jenkins.war 
  sudo: yes
          
- name: copy jenkins plugins from project
  raw: "cp -fR {{ jenkins_plugins_dir }}/*.jpi /var/lib/jenkins/plugins/"  
  sudo: yes
          
- name: copy jenkins config
  copy: src=jenkins_settings/jenkins
        dest=/etc/default/jenkins 
        owner=root group=root mode=0644
        force=true
  sudo: yes
  
- name: copy jenkins settig files
  copy: src=jenkins_settings/jenkins_home/
        dest=/var/lib/jenkins/
        force=true
  sudo: yes
 
- name: set jenkins dir attribute
  file: path=/var/lib/jenkins
        state=directory recurse=yes
        owner=jenkins group=jenkins
  sudo: yes
          
- name: set jenkins private key attribute
  file: path=/var/lib/jenkins/.ssh/acceptance/private-key.pem
        owner=jenkins group=jenkins mode=0600
  sudo: yes
          
- name: setup jenkins user (pass=jenkins)
  user: name=jenkins shell=/bin/bash 
        group=jenkins groups=sudo 
        password=$1$SomeSalt$2CfQrAhuECQILo1TFh83m1
  sudo: yes
          
- name: restart jenkins
  service: name=jenkins state=restarted
  sudo: yes
          
