# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network "private_network", ip: "192.168.77.11"

  config.vm.provision "file", source: "home_settings/.ansible.cfg", destination: "~/.ansible.cfg"
  config.vm.provision "file", source: "home_settings/.ssh"        , destination: "~/"
  config.vm.provision "file", source: "../../ansible/"            , destination: "~/"

  config.vm.provision "shell" do |s|
    s.path = "init.sh"
    s.privileged = false  #rootユーザで実行するとansibleでログインできないため
  end
  
  # 開発効率を上げるために共有したほうがよいファイル
  config.vm.synced_folder "../../ansible",    "/home/vagrant/products/simple-taskboard/ansible"
  config.vm.synced_folder "../../app/api",    "/home/vagrant/products/simple-taskboard/app/api"
  
end
