# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network "private_network", ip: "192.168.77.11"

  config.vm.synced_folder "../..", "/home/vagrant/products/simple-taskboard", 
  	type: "rsync", 
  	rsync__exclude: ["vagrant/", "middleware/", ".git/"]

  config.vm.provision "file", source: "home_settings/.ansible.cfg", destination: "~/.ansible.cfg"
  config.vm.provision "file", source: "home_settings/.ssh"        , destination: "~/"
  config.vm.provision "file", source: "../../ansible/"            , destination: "~/"

  config.vm.provision "shell" do |s|
    s.path = "init.sh"
    s.privileged = false  #rootユーザで実行するとansibleでログインできないため
  end
  
end
