# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

HOST_PROJECT_ROOT = "C:/Users/mts/Desktop/Study/products/simple-taskboard"
GUEST_PROJECT_ROOT = "/home/vagrant/products/simple-taskboard"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.network "private_network", ip: "192.168.55.11"
  
  config.vm.synced_folder HOST_PROJECT_ROOT, GUEST_PROJECT_ROOT, :mount_options => ["dmode=777","fmode=666"] 
                                       # ファイル同期でファイルに実行権がついてしまうとansibleのインベントリファイルが正しく認識できないため
  config.vm.provision "shell" do |s|
    s.path = "provision/shell/init.sh"
    s.args = [ GUEST_PROJECT_ROOT ]
    s.privileged = false               #rootユーザで実行するとansibleでログインできないため
  end
end
