---

- name: stop api server
  command: wget -q -O - --post-data=a http://localhost:{{item}}/api/manage/shutdown
  sudo: yes
  ignore_errors: True
  with_items: api_ports
  
- name: backup api module
  raw: cp {{api_deploy_path}}/* {{api_deploy_path}}/backup/
  sudo: yes
  ignore_errors: True

- name: deploy api module
  copy: src={{item}} dest={{api_deploy_path}}/
  sudo: yes
  with_items:
    - dist/api.jar
    - app_config/application.properties

- name: start api server
  shell: nohup java -jar "{{api_deploy_path}}/api.jar" --server.port={{item}} & 
         chdir="{{api_deploy_path}}"
  sudo: yes
  with_items: api_ports
