---
- hosts: dev
  tasks:
    - name: install vim
      apt: name=vim state=present
      sudo: yes

    - name: install git
      apt: name=git state=present
      sudo: yes
    - name: set git editor
      command: git config --global core.editor 'vim -c "set fenc=utf-8"'

    - name: intall nvm
      shell: wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.17.3/install.sh | bash
      ignore_errors: True
    - name: intall node.js
      raw: source /home/vagrant/.nvm/nvm.sh && nvm install 0.10

    - name: install node modules
      npm: name={{ item }} global=yes executable=/home/vagrant/.nvm/v0.10.33/bin/npm
      with_items:
        - yo
        - bower
        - grunt




