VAGRANTFILE_API_VERSION = "2"

Dotenv.load

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "dummy"
 
  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "#{ENV['AWS_ACCESS_KEY_ID']}"
    aws.secret_access_key = "#{ENV['AWS_SECRET_ACCESS_KEY']}"
    aws.keypair_name = "vagrant-aws"

    aws.ami = "ami-e74b60e6"
    aws.instance_type = "t2.micro"
    aws.security_groups = [ 'vagrant', 'jenkins' ]
    aws.region = "ap-northeast-1" # "Tokyo"
    aws.availability_zone = "ap-northeast-1a"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "home_settings/.ssh/vagrant-aws.pem"
  end
  
  config.vm.provision "file", source: "home_settings/.ansible.cfg", destination: "~/.ansible.cfg"
  config.vm.provision "file", source: "home_settings/.ssh"        , destination: "~/"
  config.vm.provision "file", source: "../../ansible/"            , destination: "~/"  
  
  config.vm.provision "shell" do |s|
    s.path = "init.sh"
    s.privileged = false               #rootユーザで実行するとansibleでログインできないため
  end  
 
end