---

- name: copy custom home settings
  copy: src=home_settings/ dest={{ home_dir }}/ 
        mode=0644

- name: install tools
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - vim
    - curl
    - git
    - python-software-properties
    - xvfb
    - libfontconfig
      # libfontconfig is needed for phantomjs running

- name: checkout neobundle.vim
  git: repo=https://github.com/Shougo/neobundle.vim.git
       dest={{ home_dir }}/.vim/bundle/neobundle.vim
  
- name: set git editor
  command: git config --global core.editor 'vim -c "set fenc=utf-8"'
          
- name: set git credential helper
  command: git config --global credential.helper store
          
- name: add chrome apt-key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  sudo: yes

- name: add chrome to apt source.list
  raw: echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list 
  sudo: yes
          
- name: install chrome
  apt: name=google-chrome-stable state=present update_cache=yes
  sudo: yes
  
