---

- name: copy custom home settings
  copy: src=home_settings/ dest={{ home_dir }}/ 
        mode=0644

- name: install tools
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - vim
    - curl
    - git
    - libfontconfig
      # libfontconfig is needed for phantomjs running

- name: checkout neobundle.vim
  git: repo=https://github.com/Shougo/neobundle.vim.git
       dest={{ home_dir }}/.vim/bundle/neobundle.vim
  
- name: set git editor
  command: git config --global core.editor 'vim -c "set fenc=utf-8"'
          
- name: set git credential helper
  command: git config --global credential.helper store
  
