VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "dummy"
 
  # config.vm.synced_folder "../..", "/home/ubuntu/vagrant", disabled: true

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "xxx"
    aws.secret_access_key = "yyy"
    aws.keypair_name = "vagrant-aws"

    aws.ami = "ami-e74b60e6"
    aws.instance_type = "t2.micro"
    aws.security_groups = [ 'vagrant', 'jenkins' ]
    aws.region = "ap-northeast-1" # "Tokyo"
    aws.availability_zone = "ap-northeast-1a"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "./provision/shell/vagrant-aws.pem"
  end
  
  config.vm.provision "shell" do |s|
    s.path = "provision/shell/init.sh"
    s.privileged = false               #rootユーザで実行するとansibleでログインできないため
  end  
 
end